package me.blackjack.terminal.impl.constant

internal object KeyCodes {

    const val ESC = 27

    private const val WINDOWS_ARROW_DESIGNATOR = 79
    private const val UNIX_ARROW_DESIGNATOR = 91

    private const val ARROW_UP = 65
    private const val ARROW_DOWN = 66
    private const val ARROW_RIGHT = 67
    private const val ARROW_LEFT = 68

    val WINDOWS_ARROW_UP_SEQUENCE = listOf(ESC, WINDOWS_ARROW_DESIGNATOR, ARROW_UP)
    val WINDOWS_ARROW_DOWN_SEQUENCE = listOf(ESC, WINDOWS_ARROW_DESIGNATOR, ARROW_DOWN)
    val WINDOWS_ARROW_RIGHT_SEQUENCE = listOf(ESC, WINDOWS_ARROW_DESIGNATOR, ARROW_RIGHT)
    val WINDOWS_ARROW_LEFT_SEQUENCE = listOf(ESC, WINDOWS_ARROW_DESIGNATOR, ARROW_LEFT)

    val UNIX_ARROW_UP_SEQUENCE = listOf(ESC, UNIX_ARROW_DESIGNATOR, ARROW_UP)
    val UNIX_ARROW_DOWN_SEQUENCE = listOf(ESC, UNIX_ARROW_DESIGNATOR, ARROW_DOWN)
    val UNIX_ARROW_RIGHT_SEQUENCE = listOf(ESC, UNIX_ARROW_DESIGNATOR, ARROW_RIGHT)
    val UNIX_ARROW_LEFT_SEQUENCE = listOf(ESC, UNIX_ARROW_DESIGNATOR, ARROW_LEFT)

    val ARROW_UP_SEQUENCE = listOf(WINDOWS_ARROW_UP_SEQUENCE, UNIX_ARROW_UP_SEQUENCE)
    val ARROW_DOWN_SEQUENCE = listOf(WINDOWS_ARROW_DOWN_SEQUENCE, UNIX_ARROW_DOWN_SEQUENCE)
    val ARROW_RIGHT_SEQUENCE = listOf(WINDOWS_ARROW_RIGHT_SEQUENCE, UNIX_ARROW_RIGHT_SEQUENCE)
    val ARROW_LEFT_SEQUENCE = listOf(WINDOWS_ARROW_LEFT_SEQUENCE, UNIX_ARROW_LEFT_SEQUENCE)

    const val CARRIAGE_RETURN = 13
    const val BACKSPACE = 8

}